add_newline = false
command_timeout = 1000

format = """
$character\
$os$hostname\
$directory\
$git_branch\
$git_status \
$python\
$aws\
$golang\
$java\
$nodejs\
$rust\
$ruby\
$scala\
$dart\
$conda\
$pijul_channel\
$lua\
$rlang\
$package\
$buf\
$memory_usage\
$fill \
$cmd_duration \
[](#1C3A5E)$time[](#1C3A5E)
[└─>](bold green) """

continuation_prompt = '▶▶ '

[fill]
symbol = ' '

[time]
disabled = false
time_format = "%r" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ 󱑍 $time ](bg:#1C3A5E fg:#8DFBD2)]($style)'

[cmd_duration]
format = ' last command: [$duration](bold)'

[os]
format = '[$symbol](bold) '
disabled = false

[os.symbols]
Macos = '󰀵'

# Shows the hostname
[hostname]
ssh_only = false
format = 'on [$hostname](bold) '
disabled = false
ssh_symbol = " "

# Shows current directory
[directory]
truncation_length = 2
fish_style_pwd_dir_length=3

# Shows current git branch
[git_branch]
symbol = " "
format = 'via [$symbol$branch]($style)'
# truncation_length = 4
truncation_symbol = '…/'
style = 'bold'

# Shows current git status
[git_status]
format = '[ $all_status$ahead_behind]($style)'
style = 'bold'
conflicted = '🏳'
up_to_date = ''
untracked = ' '
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
stashed = ' '
modified = ' '
staged = '[++\($count\)](green)'
renamed = '襁 '
deleted = ' '

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[golang]
symbol = " "

[java]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "
disabled = false
style='bold dimmed'
threshold = 1
format = "$symbol [${ram}(|${swap})]($style) "

[nodejs]
symbol = " "

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = " "

[python]
symbol = " "
pyenv_version_name = true

[ruby]
symbol = " "

[rlang]
symbol = "󰟔 "

[rust]
symbol = " "

[scala]
symbol = " "
